name: Hello, publicplan!
description: A GitHub Action that prints "Hello, publicplan!" to the console.
author: Roland Awemo.

inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: 'publicplan'

outputs:
  time: 
    description: The time we greeted you.

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}