name: GitHub Actions Demo

on:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: environment
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo triggering event
        run: |
          echo 🎉 The tiggering event was ${{ github.event_name }}!
          echo 🪾 The event was run on ${{ github.ref }}
      - uses: actions/checkout@v4
      - name: list
        run: |
          echo 📋 The files in the repository are:
          tree
  
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Echo triggering event
        run: |
          echo Testing...
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Echo triggering event
        run: |
          echo Testing...
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Build, Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: inputs.environment == 'Production'
    steps:
      - name: Deploy to Production
        run: |
          echo Step 1 deploying...
          sleep 10
          echo Step 2 deploying...
          sleep 10
          echo Step 3 deploying...
          sleep 10
          echo Step 4 deploying...
          sleep 10
          echo Step 5 deploying...
          sleep 10
          echo 🚀
