name: GitHub Actions Demo
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo triggering event
        run: echo ${{ github.event_name }}
      - name: Echo branch event
        run: echo ${{ github.ref }}
      - name: list
        run: ls ${{ github.workspace }}
