name: GitHub Actions Demo

on:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo triggering event
        run: |
          echo 🎉 The tiggering event was ${{ github.event_name }}!
          echo 🪾 The event was run on ${{ github.ref }}
      - uses: actions/checkout@v4
      - name: list
        run: |
          echo 📋 The files in the repository are:
          tree
