name: Hello World Docker Action
on: 
  push:
    branches:
      - main
    paths: 
      - 'hello-world-docker-action/**'
  workflow_dispatch:

jobs:
  hello-world-docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hello World Docker Action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Roland Awemo'
          
      - name: Print greeting time
        run: echo "Greeting time was ${{ steps.hello-world-docker-action.outputs.time }}"
  